name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-material mkdocs-material-extensions --upgrade
      - run: pip install pipwin
      - run: pipwin install cairocffi
      - run: mkdocs gh-deploy --force