name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v3 # Used to install node environment - XXX https://github.com/actions/setup-node
        with:
          node-version: 18
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-material mkdocs-material-extensions --upgrade
      - run: pip install pipwin
      - run: pipwin install cairocffi
      - run: mkdocs gh-deploy --force